services:
  - type: web
    name: trustforge-app
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate --schema=apps/api/prisma/schema.prisma && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
